### ISSUE TITLE
这个爬虫规则是不是已经失效了？

### ISSUE THREAD

**Issue by chaoLR** [jinzhen-lin/scrapy_eleme#1]
现在地址都302重定向到新的页面了

**Comment by jinzhen-lin** [comment]
是，这种大公司更新反爬规则都很快的，现在的价值主要是用于参考吧。我这个是之前自用，用完就不再管了。

**Comment by chaoLR** [comment]
看你写的真的简单易懂，我python连视频都没看过。那可以在你的基础上修改哪些参数可行吗？

**Comment by jinzhen-lin** [comment]
如果是要爬饿了么和美团的话，我不大清楚他们现在的反爬模式，不过这应该不是修改一些参数就能解决的。
